name: gc_wizard
description: GC Wizard
version: 0.8.0+25

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  path_provider: any
  flutter_map: any
  flutter_map_marker_popup: ^0.1.4
  flutter_localizations:
    sdk: flutter
  provider: any
  intl: any
  prefs: any
  diacritic: ^0.1.1
  base32: any
  mask_text_input_formatter: ^1.0.6
  url_launcher: ^5.4.2
  package_info: ^0.4.0+16
  math_expressions: ^2.0.0
  pointycastle: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/logo/
    - assets/coordinates/
    - assets/symbol_tables/
    - assets/symbol_tables/arcadian/
    - assets/symbol_tables/braille/
    - assets/symbol_tables/chappe/
    - assets/symbol_tables/finger/
    - assets/symbol_tables/flags/
    - assets/symbol_tables/freemason/
    - assets/symbol_tables/freemason_v2/
    - assets/symbol_tables/glagolitic/
    - assets/symbol_tables/hexahue/
    - assets/symbol_tables/intergalactic/
    - assets/symbol_tables/lorm/
    - assets/symbol_tables/moon/
    - assets/symbol_tables/murray/
    - assets/symbol_tables/nato/
    - assets/symbol_tables/pipeline/
    - assets/symbol_tables/pixel/
    - assets/symbol_tables/postnet/
    - assets/symbol_tables/puzzle/
    - assets/symbol_tables/resistor/
    - assets/symbol_tables/romulan/
    - assets/symbol_tables/semaphore/
    - assets/symbol_tables/sign/
    - assets/symbol_tables/visitor/

flutter_icons:
  image_path: "assets/logo/circle_border_1024_gold.png"
  android: true
  ios: true